// Copyright 2023 The glassdb Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionLog_Status int32

const (
	TransactionLog_DEFAULT   TransactionLog_Status = 0
	TransactionLog_COMMITTED TransactionLog_Status = 1
	TransactionLog_ABORTED   TransactionLog_Status = 2
	TransactionLog_PENDING   TransactionLog_Status = 3
)

// Enum value maps for TransactionLog_Status.
var (
	TransactionLog_Status_name = map[int32]string{
		0: "DEFAULT",
		1: "COMMITTED",
		2: "ABORTED",
		3: "PENDING",
	}
	TransactionLog_Status_value = map[string]int32{
		"DEFAULT":   0,
		"COMMITTED": 1,
		"ABORTED":   2,
		"PENDING":   3,
	}
)

func (x TransactionLog_Status) Enum() *TransactionLog_Status {
	p := new(TransactionLog_Status)
	*p = x
	return p
}

func (x TransactionLog_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionLog_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionLog_Status) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x TransactionLog_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionLog_Status.Descriptor instead.
func (TransactionLog_Status) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0}
}

type Lock_LockType int32

const (
	Lock_UNKNOWN Lock_LockType = 0
	Lock_NONE    Lock_LockType = 1
	Lock_READ    Lock_LockType = 2
	Lock_WRITE   Lock_LockType = 3
	Lock_CREATE  Lock_LockType = 4
)

// Enum value maps for Lock_LockType.
var (
	Lock_LockType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NONE",
		2: "READ",
		3: "WRITE",
		4: "CREATE",
	}
	Lock_LockType_value = map[string]int32{
		"UNKNOWN": 0,
		"NONE":    1,
		"READ":    2,
		"WRITE":   3,
		"CREATE":  4,
	}
)

func (x Lock_LockType) Enum() *Lock_LockType {
	p := new(Lock_LockType)
	*p = x
	return p
}

func (x Lock_LockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lock_LockType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[1].Descriptor()
}

func (Lock_LockType) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[1]
}

func (x Lock_LockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lock_LockType.Descriptor instead.
func (Lock_LockType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4, 0}
}

type TransactionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TransactionLog_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=glassdb.TransactionLog_Status" json:"status,omitempty"`
	Writes        []*CollectionWrites    `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLog) Reset() {
	*x = TransactionLog{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLog) ProtoMessage() {}

func (x *TransactionLog) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLog.ProtoReflect.Descriptor instead.
func (*TransactionLog) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TransactionLog) GetStatus() TransactionLog_Status {
	if x != nil {
		return x.Status
	}
	return TransactionLog_DEFAULT
}

func (x *TransactionLog) GetWrites() []*CollectionWrites {
	if x != nil {
		return x.Writes
	}
	return nil
}

type CollectionWrites struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Writes        []*Write               `protobuf:"bytes,2,rep,name=writes,proto3" json:"writes,omitempty"`
	Locks         *CollectionLocks       `protobuf:"bytes,3,opt,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionWrites) Reset() {
	*x = CollectionWrites{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionWrites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionWrites) ProtoMessage() {}

func (x *CollectionWrites) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionWrites.ProtoReflect.Descriptor instead.
func (*CollectionWrites) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionWrites) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CollectionWrites) GetWrites() []*Write {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *CollectionWrites) GetLocks() *CollectionLocks {
	if x != nil {
		return x.Locks
	}
	return nil
}

type Write struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Suffix string                 `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"`
	// The ID of the last transaction writing to this key.
	PrevTid []byte `protobuf:"bytes,3,opt,name=prev_tid,json=prevTid,proto3" json:"prev_tid,omitempty"`
	// Types that are valid to be assigned to ValDelete:
	//
	//	*Write_Value
	//	*Write_Deleted
	ValDelete     isWrite_ValDelete `protobuf_oneof:"val_delete"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Write) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *Write) GetPrevTid() []byte {
	if x != nil {
		return x.PrevTid
	}
	return nil
}

func (x *Write) GetValDelete() isWrite_ValDelete {
	if x != nil {
		return x.ValDelete
	}
	return nil
}

func (x *Write) GetValue() []byte {
	if x != nil {
		if x, ok := x.ValDelete.(*Write_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Write) GetDeleted() bool {
	if x != nil {
		if x, ok := x.ValDelete.(*Write_Deleted); ok {
			return x.Deleted
		}
	}
	return false
}

type isWrite_ValDelete interface {
	isWrite_ValDelete()
}

type Write_Value struct {
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

type Write_Deleted struct {
	Deleted bool `protobuf:"varint,4,opt,name=deleted,proto3,oneof"`
}

func (*Write_Value) isWrite_ValDelete() {}

func (*Write_Deleted) isWrite_ValDelete() {}

type CollectionLocks struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionLock Lock_LockType          `protobuf:"varint,2,opt,name=collection_lock,json=collectionLock,proto3,enum=glassdb.Lock_LockType" json:"collection_lock,omitempty"`
	Locks          []*Lock                `protobuf:"bytes,3,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionLocks) Reset() {
	*x = CollectionLocks{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionLocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionLocks) ProtoMessage() {}

func (x *CollectionLocks) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionLocks.ProtoReflect.Descriptor instead.
func (*CollectionLocks) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionLocks) GetCollectionLock() Lock_LockType {
	if x != nil {
		return x.CollectionLock
	}
	return Lock_UNKNOWN
}

func (x *CollectionLocks) GetLocks() []*Lock {
	if x != nil {
		return x.Locks
	}
	return nil
}

type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suffix        string                 `protobuf:"bytes,1,opt,name=suffix,proto3" json:"suffix,omitempty"`
	LockType      Lock_LockType          `protobuf:"varint,2,opt,name=lock_type,json=lockType,proto3,enum=glassdb.Lock_LockType" json:"lock_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *Lock) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *Lock) GetLockType() Lock_LockType {
	if x != nil {
		return x.LockType
	}
	return Lock_UNKNOWN
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\aglassdb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n" +
	"\x0eTransactionLog\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.glassdb.TransactionLog.StatusR\x06status\x121\n" +
	"\x06writes\x18\x03 \x03(\v2\x19.glassdb.CollectionWritesR\x06writes\">\n" +
	"\x06Status\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\v\n" +
	"\aABORTED\x10\x02\x12\v\n" +
	"\aPENDING\x10\x03\"\x82\x01\n" +
	"\x10CollectionWrites\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12&\n" +
	"\x06writes\x18\x02 \x03(\v2\x0e.glassdb.WriteR\x06writes\x12.\n" +
	"\x05locks\x18\x03 \x01(\v2\x18.glassdb.CollectionLocksR\x05locks\"|\n" +
	"\x05Write\x12\x16\n" +
	"\x06suffix\x18\x01 \x01(\tR\x06suffix\x12\x19\n" +
	"\bprev_tid\x18\x03 \x01(\fR\aprevTid\x12\x16\n" +
	"\x05value\x18\x02 \x01(\fH\x00R\x05value\x12\x1a\n" +
	"\adeleted\x18\x04 \x01(\bH\x00R\adeletedB\f\n" +
	"\n" +
	"val_delete\"w\n" +
	"\x0fCollectionLocks\x12?\n" +
	"\x0fcollection_lock\x18\x02 \x01(\x0e2\x16.glassdb.Lock.LockTypeR\x0ecollectionLock\x12#\n" +
	"\x05locks\x18\x03 \x03(\v2\r.glassdb.LockR\x05locks\"\x97\x01\n" +
	"\x04Lock\x12\x16\n" +
	"\x06suffix\x18\x01 \x01(\tR\x06suffix\x123\n" +
	"\tlock_type\x18\x02 \x01(\x0e2\x16.glassdb.Lock.LockTypeR\blockType\"B\n" +
	"\bLockType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\t\n" +
	"\x05WRITE\x10\x03\x12\n" +
	"\n" +
	"\x06CREATE\x10\x04B(Z&github.com/mbrt/glassdb/internal/protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transaction_proto_goTypes = []any{
	(TransactionLog_Status)(0),    // 0: glassdb.TransactionLog.Status
	(Lock_LockType)(0),            // 1: glassdb.Lock.LockType
	(*TransactionLog)(nil),        // 2: glassdb.TransactionLog
	(*CollectionWrites)(nil),      // 3: glassdb.CollectionWrites
	(*Write)(nil),                 // 4: glassdb.Write
	(*CollectionLocks)(nil),       // 5: glassdb.CollectionLocks
	(*Lock)(nil),                  // 6: glassdb.Lock
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_transaction_proto_depIdxs = []int32{
	7, // 0: glassdb.TransactionLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: glassdb.TransactionLog.status:type_name -> glassdb.TransactionLog.Status
	3, // 2: glassdb.TransactionLog.writes:type_name -> glassdb.CollectionWrites
	4, // 3: glassdb.CollectionWrites.writes:type_name -> glassdb.Write
	5, // 4: glassdb.CollectionWrites.locks:type_name -> glassdb.CollectionLocks
	1, // 5: glassdb.CollectionLocks.collection_lock:type_name -> glassdb.Lock.LockType
	6, // 6: glassdb.CollectionLocks.locks:type_name -> glassdb.Lock
	1, // 7: glassdb.Lock.lock_type:type_name -> glassdb.Lock.LockType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_transaction_proto_msgTypes[2].OneofWrappers = []any{
		(*Write_Value)(nil),
		(*Write_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
