# Copyright 2023 The glassdb Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  deadline: "3m"

linters:
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gocritic
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  errorlint:
    errorf: false

  revive:
    rules:
      - name: "empty-block"
        disabled: true
